---
title             : "Data Exploration of the 2005-2006 School Survey on Crime and Safety"
shorttitle        : "2005-2006 SCHOOL SURVEY ON CRIME AND SAFETY"
author: 
  - name          : "Jim Wright"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "University of Oregon, Eugene, OR"
    email         : "jwrigh16@uoregon.edu"
  - name          : "Claire Zhang"
    affiliation   : "1"
affiliation:
  - id            : "1"
    institution   : "University of Oregon"
authornote: |
  This project was completed as part of a term assignment for EDLD 610: Intro to Data Science during the Fall 2019 term.
abstract: |
 INSERT ABSTRACT
  
  
  <!-- https://tinyurl.com/ybremelq -->
keywords          : "keywords"
wordcount         : "X"
bibliography      : ["r-references.bib"]
floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no
documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
#I cleaned up your libraries (I got rid of janitor since you called it directly in the second code chunk)
#I didn't see you use datapasta, knitr, or kableExtra but maybe you intend to use them later?
library(rio)
library(here)
library(tidyverse)
library(datapasta)
library(papaja)
library(knitr)
library(kableExtra)
theme_set(theme_minimal())
opts_chunk$set(echo = FALSE,
               fig.width = 6.5,
               fig.height = 8)

```

```{r load data and filter data}

safe <- import(here("data", "2006_school_safety.sav"),
               setclass = "tbl_df") %>% 
  characterize() %>% 
  janitor::clean_names() 

safe_organized <- safe %>% 
  select(school_id, urban, level, minority, enroll, tt_cm, tt_dp, tt_s, tt_wsvb, tt_pbi, disc_rec, inc_rec, inc_rep_po, oss)

safe_organized <- safe_organized %>% 
  mutate(total_discipline_actions = disc_rec + inc_rec + inc_rep_po + oss) %>% 
  rename(teacher_training_classroom_management = tt_cm,
         teacher_training_discipline_policies = tt_dp,
         teacher_training_safety_procedures = tt_s,
         teacher_training_early_warning_signs_for_violent_behavior = tt_wsvb,
         teacher_training_positive_behavioral_intervention = tt_pbi,
         disciplinary_actions_recorded = disc_rec, 
         incidents_recorded = inc_rec,
         incidents_reported_to_police = inc_rep_po,
         out_of_school_suspensions = oss,
         urbanicity = urban,
         minority_percentage = minority, 
         enrollment = enroll)

head(safe_organized)

mean_discipline_actions <- safe_organized %>% 
  summarize(mean(total_discipline_actions))
```


``` {r tidy-data1}

tidy_disc1 <- safe_organized %>% 
  pivot_longer(
    cols = c(disciplinary_actions_recorded, incidents_recorded, incidents_reported_to_police, out_of_school_suspensions),
    names_to = "discipline_type",
    values_to = "total"
  ) %>% 
  filter(total_discipline_actions >= 159 & 
         teacher_training_classroom_management == "no" & 
         teacher_training_positive_behavioral_intervention == "no" &
         teacher_training_discipline_policies == "no" &
         teacher_training_early_warning_signs_for_violent_behavior == "no" &
         teacher_training_safety_procedures == "no")

```

```{r plots-tidydisc1}

ggplot(tidy_disc1, aes(urbanicity, total_discipline_actions)) +
  geom_col(position = "dodge", fill = "blue") +
  facet_wrap(~level, nrow = 1) +
  theme_minimal() +
  theme(plot.title = element_text(color = "red", size = 12, face = "bold", hjust = 0.5)) +
  scale_fill_discrete(name = "Discipline Type", labels = c("Disciplinary Actions Recorded", 
                                                           "Incidents Recorded",
                                                           "Incidents Reported to Police",
                                                           "Out of School Suspensions")) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(x = "School Urbanicity Level",
       y = "Total Disciplinary Actions",
       title = "Disciplinary Actions by School Urbanicity and Level \nWhere No Form of Teacher Training was Provided",
       tage = "(1)", 
       fill = "School Level")
  

ggplot(tidy_disc1, aes(minority_percentage, total_discipline_actions)) +
  geom_col(position = "dodge", fill = "blue") +
  facet_wrap(~enrollment, nrow = 1) +
  theme_minimal() +
  scale_fill_discrete(name = "Discipline Type", labels = c("Disciplinary Actions Recorded", 
                                                           "Incidents Recorded",
                                                           "Incidents Reported to Police",
                                                           "Out of School Suspensions")) +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(plot.title = element_text(color = "red", size = 9, face = "bold", hjust = 0.5)) +
  labs(x = "Minority Percentage",
       y = "Total Disciplinary Actions",
       title = "Disciplinary Actions by School Enrollment and Minority Percentage \nWhere No Form of Teacher Training was Provided",
       tage = "(2)",
       fill = "Total Enrollment")  
```

```{r descriptives tidydisc1}
knitr::kable(tidy_disc1,
             caption = "Statistics for Schools Without Teacher Training and Above Average Total Disciplinary Actions")

tidy_table1 <- tidy_disc1 %>% 
  group_by(school_id, urbanicity, level, minority_percentage, enrollment) %>% 
  summarize(sum(total_discipline_actions))

apa_table(tidy_table1, 
          caption = "Total Disciplinary Actions for Schools Not Providing Any Form of Teacher Training by School Category")

```

```{r tidy-data2}

tidy_disc2 <- tidy_disc1 %>% 
  pivot_wider(
    names_from = "discipline_type",
    values_from = "total"
  )

```

```{r plots-tidydisc2}
ggplot(tidy_disc2, aes(disciplinary_actions_recorded, incidents_recorded)) +
  geom_point(aes(color = minority_percentage), position = "jitter") +
  facet_wrap(~enrollment, nrow = 1) +
  theme_minimal() +
  scale_fill_discrete(name = "Minority Percentage", labels = c("Less than 5 Percent",
                                                               "5 to 20 Percent",
                                                               "20 to 50 Percent",
                                                               "50 Percent or More")) +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(plot.title = element_text(color = "red", size = 12, face = "bold", hjust = 0.5)) +
  labs(x = "Total Disciplinary Actions Recorded",
       y = "Total Incidents Recorded",
       title = "Relationship of Total Disciplinary Actions Recorded \nand Total Incidents Recorded \nby School Enrollment and Minority Percentage",
       tage = "(3)",
       fill = "School Enrollment")


ggplot(tidy_disc2, aes(incidents_reported_to_police, out_of_school_suspensions)) +
  geom_point(aes(color = urbanicity), position = "jitter") +
  facet_wrap(~level, nrow = 1) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Total Disciplinary Actions Recorded",
       y = "Total Incidents Recorded",
       title = "Relationship of Total Incidents Reported \nto Police and Total Out of School Suspensions \nby School Level and Urbanicity",
       tage = "(4)",
       fill = "School Level")
```

```{r descriptives tidydisc2}
knitr::kable(tidy_disc2,
             caption = "Statistics for for Schools Without Teacher Training and Above Average Total Disciplinary Actions") 

tidy_table2 <- tidy_disc2 %>% 
  group_by(school_id, total_discipline_actions, incidents_recorded, incidents_reported_to_police, out_of_school_suspensions) %>% 
  summarize(sum(total_discipline_actions))

apa_table(tidy_table2, 
          caption = "Total Disciplinary Actions for Schools Not Providing Any Form of Teacher Training by Specific Form of Discipline")
```

```{r models safe_organized_all selected data}

mod1 <- lm(total_discipline_actions ~ urbanicity + enrollment, data = safe_organized)
  
summary(mod1)

mod1_summary <- safe_organized %>% 
  group_by(urbanicity, enrollment) %>% 
  summarize(total_discipline_actions = sum(total_discipline_actions))

apa_table(mod1_summary, 
          caption = "Regression Results displaying Total Disciplinary Actions Predicted by School Urbanicity when Controlling for School Enrollment")

mod2 <- lm(total_discipline_actions ~ urbanicity + enrollment + level, data = safe_organized)

summary(mod2)

mod2_summary <- safe_organized %>% 
  group_by(urbanicity, enrollment, level) %>% 
  summarize(total_discipline_actions = sum(total_discipline_actions))


apa_table(mod2_summary, 
          caption = "Regression Results displaying Total Disciplinary Actions Predicted by School Urbanicity when Controlling for School Enrollment and Level")


mod3 <- lm(total_discipline_actions ~ urbanicity + enrollment + level + minority_percentage, data = safe_organized)
summary(mod3)


mod3_summary <- safe_organized %>% 
  group_by(urbanicity, enrollment, level, minority_percentage) %>% 
  summarize(total_discipline_actions = sum(total_discipline_actions)) %>% 
  na.omit()

apa_table(mod3_summary, 
          caption = "Regression Results displaying Total Disciplinary Actions Predicted by School Urbanicity when Controlling for School Enrollment, Level, and Minority Percentage")


```

```{r descriptives all selected data}
summary(safe_organized)

ggplot(safe_organized) +
  geom_bar(aes(urbanicity, fill = level),
           position = "dodge") +
  theme_minimal() +
  labs(x = "School Urbanicity Category with Fill of School Level", 
       y = "Total",
       title = "Number of Schools per Urbanicity and Level",
       tag = "(5)",
       fill = "School level")

ggplot(safe_organized) +
  geom_bar(aes(urbanicity, fill = level),
           position = "dodge") +
  facet_wrap(~enrollment, nrow = 1) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "School Urbanicity Category with Fill of School Level Faceted by School Enrollment", 
       y = "Total",
       title = "Number of Schools per Urban Category and Level",
       tag = "(6)")

ggplot(safe_organized, aes(out_of_school_suspensions, disciplinary_actions_recorded)) +
  geom_point(aes(color = enrollment), position = "jitter") +
  geom_smooth() +
  theme_minimal() +
  theme(plot.title = element_text(color = "red", size = 10, face = "bold", hjust = 0.5)) +
  labs(x = "Total Number of Out of School Suspensions", 
       y = "Total Number Disciplinary Actions",
       title = "Relationship Between Out of School Suspensions and \nReported Disciplinary Actions",
       tag = "(7)",
       fill = "School Enrollment")

ggplot(safe_organized) +
  geom_bar(aes(x = urbanicity, fill = teacher_training_classroom_management), 
           position = "dodge") +
  facet_wrap(~enrollment, nrow = 1) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(plot.title = element_text(color = "blue", size = 12, face = "bold", hjust = 0.5)) +
  labs(x = "School Urbanicity Category", 
       y = "Number of Schools",
       title = "The Provision of Teacher Training \non Classroom Management \nby School Urbanicity and Enrollment",
       tag = "(8)",
       fill = "Classroom \nManagement \nTeacher Training")

ggplot(safe_organized) +
  geom_bar(aes(x = urbanicity, fill = teacher_training_positive_behavioral_intervention), 
           position = "dodge") +
  facet_wrap(~enrollment, nrow = 1) +
  theme_minimal() +
  theme(plot.title = element_text(color = "blue", size = 12, face = "bold", hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "School Urbanicity Category", 
       y = "Number of Schools",
       title = "The Provision of Teacher Training \n on Positive Behavioral Intervention \n by Urbanness and Enrollment of School",
       tag = "(9)",
       fill = "Positive \nBehavioral \nIntervention")

```

```{r, relationship between teacher training and student suspension, include=TRUE}
tt_oss <- safe_organized %>% 
  pivot_longer(cols = c("teacher_training_classroom_management",
                        "teacher_training_discipline_policies", 
                        "teacher_training_safety_procedures",
                        "teacher_training_early_warning_signs_for_violent_behavior",
                        "teacher_training_positive_behavioral_intervention"),
    names_to = "training",
    names_prefix = "teacher_training_",
    values_to = "status")

ggplot(tt_oss, aes(x = training, y = total_discipline_actions, fill = status), 
           position = "dodge") +
  geom_boxplot() +
  ylim(0, 1000) +
  theme_minimal() +
  labs(x = "Teacher Training Category", 
       y = "Total Number of Outshool Suspension",
       title = "Relationship Between Teacher Training and Student Suspension",
       tag = "(5)",
       fill = "Training") +
  coord_flip()
# (0, 1000)?


mod4 <- lm(total_discipline_actions ~ training, data = tt_oss)
  
summary(mod4)

mod4_summary <- tt_oss %>% 
  group_by(training) %>% 
  summarize(total_discipline_actions = sum(total_discipline_actions))

apa_table(mod4_summary, 
          caption = "Regression Results displaying Total Disciplinary Actions Predicted by Provision of Type of Teacher Training")
```

# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
